version: '3.5'
services:
  OrderService:
   image: ${DOCKER_REGISTRY-}orderservice:v1
   build:
    context: ./OrderService
    dockerfile: Dockerfile
   environment:
    - ASPNETCORE_ENVIRONMENT=Development
   ports:
    - "4202:80"
  PaymentService:
   image: ${DOCKER_REGISTRY-}paymentservice:v1
   build:
    context: ./PaymentService
    dockerfile: Dockerfile
   environment:
    - ASPNETCORE_ENVIRONMENT=Development
   ports:
    - "4203:80"
  NotificationService:
   image: ${DOCKER_REGISTRY-}notificationservice:v1
   build:
    context: ./NotificationService
    dockerfile: Dockerfile
   environment:
    - ASPNETCORE_ENVIRONMENT=Development
   ports:
    - "4201:80"

   